### ISSUE TITLE
Docker Pull Error, Repository No Longer Exists

### ISSUE THREAD

**Issue by nkreiger** [triggermesh/triggermesh#1042]
➜  ~ docker pull gcr.io/triggermesh/knative-lambda-python37:v1.19.0
Error response from daemon: pull access denied for gcr.io/triggermesh/knative-lambda-python37, repository does not exist or may require 'docker login': denied: Permission denied for "v1.19.0" from request "/v2/triggermesh/knative-lambda-python37/manifests/v1.19.0".

Having issues across the board applying new resources because it is no longer able to pull the image

**Comment by ajp-lsq** [comment]
As an fyi the latest helm chart (v0.5.1) also references a now non-existent docker image (gcr.io/triggermesh/triggermesh-controller:v1.18.1)

**Comment by sebgoa** [comment]
thanks for bring it up, we will fix the charts cc/ @sameersbn

**Comment by sameersbn** [comment]
Sorry about the late  been fixed reply. This issue should have been
resolved by now. @***@***.*** ***@***.***> can you
please try again?

**Comment by danylo-omelchenko** [comment]
I'm having trouble getting v1.13.0 as well

**Comment by sebgoa** [comment]
@nkreiger v1.19.0 is back. sorry about this

**Comment by sebgoa** [comment]
@ajp-lsq v1.18.1 is also back

**Comment by sameersbn** [comment]
@danylo-omelchenko you should now be able to get the v1.13.0 images. sorry about the glitch.
