### ISSUE TITLE
AWS Spec Credentials Should Match in Targets and Sources

### ISSUE THREAD

**Issue by JeffNeff** [triggermesh/triggermesh#1114]
Currently, the naming of the spec parameters for the credentials do not match with our AWS Source and Targets. 

see:
 * https://github.com/triggermesh/triggermesh/blob/main/config/samples/targets/aws/200-aws-sqs-target.yaml 
 * https://github.com/triggermesh/triggermesh/blob/main/config/samples/sources/awssqssource.yaml

Requirements
* the Target spec should match the Source 
* No migration needed

**Comment by jmcx** [comment]
Assiging to Jeff and Sameer to keep it in view.

**Comment by jmcx** [comment]
we need to solve this asap
