### ISSUE TITLE
[QUESTION] Including Keptn CloudEvents

### ISSUE THREAD

**Issue by agardnerIT** [triggermesh/triggermesh#1130]
Keptn defines it's cloudevents here: https://github.com/keptn/spec/blob/master/cloudevents.md

How would I create a PR to include these events in triggermesh? Is it as easy as including the schemas into the schemas folder here? Presumable one event per file?

Final question: Aside from the "standard" events you see on the page above, Keptn has `sequence` level events and `task` level events which can take a dynamic name.

For example, triggering a sequence called `hello` in the `dev` stage, the `type` would be: `sh.keptn.event.dev.hello.triggered` with `hello` being dynamic depending on what the user decides. So how would that be referenced here?

Probably more important is the dynamic task level cloudevent. For a task called `foo` it would be: `sh.keptn.event.foo.triggered`. Notice the lack of a stage (this is given in the `data` block of the ce). A user is free to choose any arbitrary task name but all tasks have the same minimal mandatory fields.

**Comment by sebgoa** [comment]
Hi Adam,

TriggerMesh can ingest any CloudEvent through its CloudEvent source: https://docs.triggermesh.io/guides/cloudeventssource/#configuring-credentials-optional

I am happy to discuss your use case further, let's connect via email sebgoa@triggermesh.com

**Comment by sebgoa** [comment]
I am closing this because the CloudEvents source could be used as an endpoint for keptnevents

https://docs.triggermesh.io/1.24/sources/cloudevents/

feel free to re-open
