### ISSUE TITLE
[BUG] Transformation race condition causing values to overlap

### ISSUE THREAD

**Issue by nkreiger** [triggermesh/triggermesh#1133]
This logic:

https://github.com/triggermesh/triggermesh/blob/main/pkg/flow/adapter/transformation/adapter.go#L97-L109

happening on instantiation of the adapter makes it nice and re-usable, however, it causes a bug when receiving and performing transformations at high traffic.

I believe it has to do with the common storage, and the creation of the context and data pipelines outside the scope of where cloud events are received.

Recreate?

1. Setup a basic transformation to store the `$id` and assign it to an arbitrary place in the payload body
2. Run a script (in my case it was multiple go routinues) that concurrently sends events against the transformation...I only had to do 10 to reproduce this issue
3. You will see that the id overlaps...aka an id from a different cloud event transaction http scope, gets assigned to the ID of another one because of the shared values overwriting each other at high traffic

**Comment by nkreiger** [comment]
fixed by:
https://github.com/triggermesh/triggermesh/pull/1134

**Comment by JeffNeff** [comment]
so question... when you did this.. did you send the events directly to the adapter or did you use a broker?
