### ISSUE TITLE
[Question] Is it possible to use `aadpodidbinding` or AKS managed identity

### ISSUE THREAD

**Issue by imaness** [triggermesh/triggermesh#1168]
Is AKS Pod managed identity supported for using any of the Azure Sources/Targets? Looking at the yaml schema, seems like it clientId and clientSecret are both required.

**Comment by imaness** [comment]
Azure Service Bus and Storage Account.  Thanks

**Comment by sebgoa** [comment]
ok, thanks, let us see how we can put this in the roadmap

**Comment by sebgoa** [comment]
Hi @imaness  Fran added support for AKS managed identity. We have not cut a release yet but it is available via the CircleCI build.

It would be great to get validation from you that it works as expected in your environment.

**Comment by sebgoa** [comment]
The manifests for the unreleased version that contains this AKS support is at:

https://app.circleci.com/pipelines/github/triggermesh/triggermesh/3246/workflows/d0b19b54-e8fb-4127-8d19-322cb2b7fc49/jobs/9019/artifacts

You should be able to apply the manifests
