### ISSUE TITLE
adapterOverrides not working on releases 1.16.1, 1.16.0

### ISSUE THREAD

**Issue by DaripS** [triggermesh/triggermesh#1171]
The resource parameters provided for adapterOverrides don't take effect on the awssqssource. The pods are running into out of memory as the default resources provided are low. I'm trying to find a way to override the default resources provided. Appreciate the help.

**Comment by tzununbekov** [comment]
@DaripS I just checked - resource parameters overrides work as expected. How the default resources are set in your cluster?

**Comment by tzununbekov** [comment]
I just noticed that you mentioned old versions of TriggerMesh. Adapter Overrides were introduced in 1.16.1 and should work fine there, but 1.16.0 certainly does not support it.

**Comment by odacremolbap** [comment]
@DaripS is your problem solved by using a recent TriggerMesh release?

**Comment by odacremolbap** [comment]
Closing since this should be solved when using newer versions.
