### ISSUE TITLE
Standardize naming scheme of programs cmd and config manifests

### ISSUE THREAD

**Issue by cab105** [triggermesh/triggermesh#12]
The naming convention of their prior homes were ported over to initially get the code in place first. This task ensures that it is addressed.

**Comment by antoineco** [comment]
Adding the renaming of files under `config` to the scope because it feels closely related.

E.g. we have things such as

```
300-slack-crd.yaml
300-slacksource.yaml
```

In the above example, `slack` should be `slacktarget`, and we may be able to drop the "-crd" suffix since `300-` files are CRDs by convention (open to discussion).
