### ISSUE TITLE
Support IAM role auth in AWS targets

### ISSUE THREAD

**Issue by Eric84626** [triggermesh/triggermesh#1238]
Hello,
I find aws targets are not able to support iam role auth like aws sources(sqs, s3, sns).
Sometimes we are not allowed to use IAM user, and can't use AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY for aws credentials. 
Would you help to confirm if you have plan use AssumeRoleWithWebIdentity for aws targets like aws sources(sqs, s3, sns)?

Thanks

**Comment by tzununbekov** [comment]
Hi @Eric84626, thanks for pointing out this issue.
We'll schedule the patch in our next release cycle which I believe should happen this month. I'll let you know in the comments when the issue's status changes.

**Comment by Eric84626** [comment]
@tzununbekov 
Great news, thanks a lot for your confirm.

**Comment by tzununbekov** [comment]
@Eric84626 IAM role auth support is added in #1243 and will be available in the next TriggerMesh release (or in the CI build artifacts for dev version if needed sooner). Please note that AWS Target CRDs were changed to match AWS Sources schema.
You're welcome to join our Slack: https://join.slack.com/t/triggermesh-community/shared_invite/zt-1kngevosm-MY7kqn9h6bT08hWh8PeltA

**Comment by Eric84626** [comment]
@tzununbekov  Thanks for your update.

**Comment by jmcx** [comment]
@Eric84626 this is now available in TriggerMesh 1.23: https://github.com/triggermesh/triggermesh/releases/tag/v1.23.0

Cheers
