### ISSUE TITLE
Broken link in README: Guides

### ISSUE THREAD

**Issue by 0xdevalias** [triggermesh/triggermesh#1250]
Just a heads up that the 'Guides' link in your README is broken, and 404's.

It currently goes to: https://docs.triggermesh.io/guides/creatingasource/

As there is no index, it's not possible to link to https://docs.triggermesh.io/guides/ (which 403's)

So navigating from https://docs.triggermesh.io/, the first entry under the Guides heading is https://docs.triggermesh.io/guides/creatingadls/, so maybe that's a good place to link? Though given it's a very specific use case, maybe this guide on connecting to slack provides a more 'general end to end overview' that would make a good first start: https://docs.triggermesh.io/guides/webhook-to-slack/

Alternately.. it might be good to have a general 'intro to the guides' page in those docs, that then could be linked to, as it feels a little weird jumping straight into a specific guide.

**Comment by sebgoa** [comment]
Yes that's not good.

We should put an index page.

The source is actually at https://github.com/triggermesh/docs/blob/main/mkdocs.yml

**Comment by odacremolbap** [comment]
Fixed by https://github.com/triggermesh/triggermesh/pull/1252

**Comment by 0xdevalias** [comment]
Further improved by:

- https://github.com/triggermesh/docs/issues/328
