### ISSUE TITLE
Allow setting labels on adapters

### ISSUE THREAD

**Issue by snuggie12** [triggermesh/triggermesh#1275]
We have OPA policies in place for `Deployments`, `Pods`, and `Services`. I don't entirely follow the conversation in https://github.com/triggermesh/triggermesh/issues/705 but if this is already possible please let me know how.

If not possible it'd be great if that could be added. I had tried to add a label to `GoogleCloudPubSubSource` but I didn't see label transfer in the code like I did with the annotation for workload identity.

**Comment by tzununbekov** [comment]
All correct, although thread in #705 is relevant to your question, the `adapterOverrides` [implementation](https://github.com/triggermesh/triggermesh/blob/v1.23.0/pkg/apis/common/v1alpha1/types.go#L39-L49) does not include adapter labels override at this moment. We could probably extend adapter overrides to include labels or just make adapter deployments inherit the parent object meta attributes.

**Comment by sebgoa** [comment]
@tzununbekov related: https://github.com/triggermesh/triggermesh/issues/768

**Comment by snuggie12** [comment]
I leave the implementation to you all obviously, but I do think the `adapterOverrides` is the more intuitive location.

I've recently started learning to program and I started with golang. I was reading some devs are against overloading `context` with too many values. Purely from wanting to learn, but if you do go with that solution for `labels` I'd like to hear thoughts on that statement.

**Comment by tzununbekov** [comment]
"Label overrides" support added in #1278, and will be available in our next release. I'll post links to dev builds after we merge it with the upstream.

Regarding the `context`, I personally agree with the opinion that it should not be abused as a values storage, however, there are a lot of [examples](https://github.com/knative/pkg/search?q=context.WithValue) where this is practiced without any problems.

**Comment by tzununbekov** [comment]
https://app.circleci.com/pipelines/github/triggermesh/triggermesh/3505/workflows/93ba47c9-99f0-4cc0-afc8-f2cc590112e2/jobs/9720/artifacts

@snuggie12 please let us know if this helped in your case

**Comment by automaticgiant-ml** [comment]
yeah that's working, @tzununbekov 
thanks
do you have an expected release date?

**Comment by tzununbekov** [comment]
Glad that it helped. I don't have the date for our next release, but you can join our slack where somebody from the team will help you out with that:
https://join.slack.com/t/triggermesh-community/shared_invite/zt-1kngevosm-MY7kqn9h6bT08hWh8PeltA

**Comment by sebgoa** [comment]
1.24 should come out on April 3rd, but we will see about doing a patch release next week if that can help you

**Comment by sebgoa** [comment]
@snuggie12 any thoughts on this fix https://github.com/triggermesh/triggermesh/issues/1299 that allows individual SA per adapter on the same namespace ?

**Comment by sebgoa** [comment]
this is now in v1.24 which is just released so I am closing it.

@snuggie12 @automaticgiant-ml let us know how it goes. Don't hesitate to reach out on Slack.

**Comment by snuggie12** [comment]
Cool, I'll give it a go soon. Thanks for all the hard work.
