### ISSUE TITLE
tmctl on MacOS 13.0.1 w/ minikube: "docker connect: service wait timeout"

### ISSUE THREAD

**Issue by ray-harrison** [triggermesh/triggermesh#1287]
I'm on MacOS 13.0.1 running minikube 1.28.0, k8s v 1.25.3, docker v20.10.18 as the container runtime for k8s. I've installed the latest tmctl and am working to get it set up. I get this when attempting the basic example:

➜ tmctl create broker mybroker
2023/01/23 09:44:45 - | Updating manifest
2023/01/23 09:44:45 - | Starting container
Error: docker connect: service wait timeout
Usage:
  tmctl create broker <name> [flags]

Examples:
tmctl create broker foo

Flags:
  -h, --help   help for broker

Global Flags:
      --broker string    Optional broker name.
      --version string   TriggerMesh components version.

2023/01/23 09:44:58 docker connect: service wait timeout

The docker environment is:

➜ env | grep DOCKER
DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://192.168.205.11:2376
DOCKER_CERT_PATH=/Users/rharri005/.minikube/certs
MINIKUBE_ACTIVE_DOCKERD=minikube

I'm sure I'm missing something simple and fundamental. What's the best way for me to approach this?

**Comment by sebgoa** [comment]
if you run `docker ps` or `docker run` does it execute properly ?

**Comment by ray-harrison** [comment]
Yes, both commands run properly. 
-----------

 docker ps
CONTAINER ID   IMAGE                                      COMMAND                  CREATED             STATUS             PORTS                                      NAMES
c9e73f135a0f   gcr.io/triggermesh/memory-broker:latest    "/memory-broker star…"   About an hour ago   Up About an hour   0.0.0.0:54197->8080/tcp                    mybroker-broker
a8a0bbd814fe   6e38f40d628d                               "/storage-provisioner"   3 hours ago         Up 3 hours                                                    k8s_storage-provisioner_storage-provisioner_kube-system_3c919388-c04e-46b8-b124-986bae97e10f_2
07d43f6732a1   gcr.io/k8s-minikube/minikube-ingress-dns   "docker-entrypoint.s…"   2 days ago          Up 2 days                                                     k8s_minikube-ingress-dns_kube-ingress-dns-minikube_kube-system_5904e463-e547-4cf3-a27a-56ea747d0ca7_0
cce72406faf1   k8s.gcr.io/pause:3.6                       "/pause"                 2 days ago          Up 2 days                                                     k8s_POD_kube-ingress-dns-minikube_kube-system_5904e463-e547-4cf3-a27a-56ea747d0ca7_0
304a861dc597   k8s.gcr.io/ingress-nginx/controller        "/usr/bin/dumb-init …"   2 days ago          Up 2 days                                                     k8s_controller_ingress-nginx-controller-5959f988fd-w74wn_ingress-nginx_ac2face2-0303-4e5d-8846-4cdd1f93e9aa_0
cbf60cb57b09   k8s.gcr.io/pause:3.6                       "/pause"                 2 days ago          Up 2 days          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   k8s_POD_ingress-nginx-controller-5959f988fd-w74wn_ingress-nginx_ac2face2-0303-4e5d-8846-4cdd1f93e9aa_0
bce1c943a1d0   5185b96f0bec                               "/coredns -conf /etc…"   2 days ago          Up 2 days                                                     k8s_coredns_coredns-565d847f94-tqwqr_kube-system_634f898b-ea17-4597-af84-fc58725d4dca_0
0a1f801db7e7   k8s.gcr.io/pause:3.6                       "/pause"                 2 days ago          Up 2 days                                                     k8s_POD_coredns-565d847f94-tqwqr_kube-system_634f898b-ea17-4597-af84-fc58725d4dca_0
fe818481d224   beaaf00edd38                               "/usr/local/bin/kube…"   2 days ago          Up 2 days                                                     k8s_kube-proxy_kube-proxy-z7nbr_kube-system_9b0ff4d4-a04a-44f6-9cfe-eb770293df93_0
89a700dc8057   k8s.gcr.io/pause:3.6                       "/pause"                 2 days ago          Up 2 days                                                     k8s_POD_storage-provisioner_kube-system_3c919388-c04e-46b8-b124-986bae97e10f_0
77540881fd95   k8s.gcr.io/pause:3.6                       "/pause"                 2 days ago          Up 2 days                                                     k8s_POD_kube-proxy-z7nbr_kube-system_9b0ff4d4-a04a-44f6-9cfe-eb770293df93_0
49b77fd3aaa3   0346dbd74bcb                               "kube-apiserver --ad…"   2 days ago          Up 2 days                                                     k8s_kube-apiserver_kube-apiserver-minikube_kube-system_0ba511715d9e3817a30cbd7c60432703_0
5931383a6a4a   a8a176a5d5d6                               "etcd --advertise-cl…"   2 days ago          Up 2 days                                                     k8s_etcd_etcd-minikube_kube-system_39c4f71c3c3f4538f457532743480c94_0
1ca95c204c26   603999231275                               "kube-controller-man…"   2 days ago          Up 2 days                                                     k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_8ff82c85c8a8a0d667f0ac73853725cc_0
cfc0aa3eebe8   6d23ec0e8b87                               "kube-scheduler --au…"   2 days ago          Up 2 days                                                     k8s_kube-scheduler_kube-scheduler-minikube_kube-system_7e6ece94cd0950fdbbf66ddae1e4c53b_0
29e908c6f0ca   k8s.gcr.io/pause:3.6                       "/pause"                 2 days ago          Up 2 days                                                     k8s_POD_kube-apiserver-minikube_kube-system_0ba511715d9e3817a30cbd7c60432703_0
d0018f2f58eb   k8s.gcr.io/pause:3.6                       "/pause"                 2 days ago          Up 2 days                                                     k8s_POD_kube-controller-manager-minikube_kube-system_8ff82c85c8a8a0d667f0ac73853725cc_0
97fe24cc6c97   k8s.gcr.io/pause:3.6                       "/pause"                 2 days ago          Up 2 days                                                     k8s_POD_etcd-minikube_kube-system_39c4f71c3c3f4538f457532743480c94_0
4649e374e9de   k8s.gcr.io/pause:3.6                       "/pause"                 2 days ago          Up 2 days                                                     k8s_POD_kube-scheduler-minikube_kube-system_7e6ece94cd0950fdbbf66ddae1e4c53b_0

---------------------------


➜ docker run -it docker/whalesay bash
Unable to find image 'docker/whalesay:latest' locally
latest: Pulling from docker/whalesay
Image docker.io/docker/whalesay:latest uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
e190868d63f8: Pull complete 
909cd34c6fd7: Pull complete 
0b9bfabab7c1: Pull complete 
a3ed95caeb02: Pull complete 
00bf65475aba: Pull complete 
c57b6bcc83e3: Pull complete 
8978f6879e2f: Pull complete 
8eed3712d2cf: Pull complete 
Digest: sha256:178598e51a26abbc958b8a2e48825c90bc22e641de3d31e18aaf55f3258ba93b
Status: Downloaded newer image for docker/whalesay:latest
root@fd58b8987e99:/cowsay#

**Comment by ray-harrison** [comment]
It shows that it is there and indeed it is online.


~/.triggermesh/cli via ⬢ v18.8.0 on 🐳 v20.10.20 (192.168.205.11) took 7m 36.0s 
➜ tmctl brokers
mybroker

~/.triggermesh/cli via ⬢ v18.8.0 on 🐳 v20.10.20 (192.168.205.11) 
➜ tmctl describe mybroker
Broker       Status
mybroker     online(http://localhost:54197)
---------------------------------------------
tmctl watch and send-event (with / without specifying broker) also get the timeout...

➜ tmctl watch mybroker
2023/01/23 11:16:06 - | Connecting to broker
Error: create container: starting container: docker connect: service wait timeout
Usage:
  tmctl watch [broker] [flags]

Examples:
tmctl watch

Flags:
  -e, --eventTypes string   Filter events based on type attribute
  -h, --help                help for watch

Global Flags:
      --broker string    Optional broker name.
      --version string   TriggerMesh components version.

2023/01/23 11:16:13 create container: starting container: docker connect: service wait timeout

**Comment by tzununbekov** [comment]
This `docker connect: service wait timeout` error means that the tmctl couldn't create TCP connection to the broker container on `0.0.0.0:54197`. Without this check passed, we cannot expect other commands to work properly because the broker being online is one of the main requirements.
The most probable cause for this issue as I see it right now is the timeout condition for the TCP connection - there is a 5 seconds wait period for the connection to be established, but the connection timeout itself is 1 second and it may be not enough in some cases.
@ray-harrison I'll make CLI's timeout parameter configurable and ping you here when it's ready to test.

**Comment by sebgoa** [comment]
@ray-harrison it would be easier to help you on Slack if you want to join our workspace: https://join.slack.com/t/triggermesh-community/shared_invite/zt-1kngevosm-MY7kqn9h6bT08hWh8PeltA

**Comment by ray-harrison** [comment]
I've joined in on Slack - the last thing I'll mention here is that minikube sets up a DOCKER_HOST that isn't localhost so attempting to connect to 0.0.0.0:<port> won't work. You can connect to DOCKER_HOST_IP:54197. Would it make sense to extend the capability to either allow users to specify docker host or pull it in automatically from docker-env?

**Comment by tzununbekov** [comment]
@ray-harrison I think you're right about the connection to 0.0.0.0. I've prepared the update triggermesh/tmctl#231 where I replaced this TCP connection check with the simple status validation based on the Docker client methods. It will be available for installation via brew after our next release, but you can test it by building `tmctl` from the [source](https://github.com/triggermesh/tmctl#source). Please let us know if this update solved the problem.

**Comment by ray-harrison** [comment]
Thank you @tzununbekov - I'll give it a go sometime today MST and let you now.

**Comment by sebgoa** [comment]
@ray-harrison this should work now, so I am closing this issue. Please re-open if you have trouble
