### ISSUE TITLE
Add a Solace source

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/triggermesh#1298]
Way back then we had a prototype Solace source, we should get it back in this repo.

the original PR was at: https://github.com/triggermesh/event-sources/pull/85/files

Solace can give us connectivity to SAP HANA.

**Comment by LarryZhangy** [comment]
@FranBarrera, i alse want to write a source&target for some saas, but I think this guide is not enough: [https://knative.dev/docs/eventing/custom-event-source/custom-event-source/](url) . 
Is there any other developer guide for it? I appreciate it if any！

**Comment by FranBarrera** [comment]
Hey @LarryZhangy We do our components a bit different than knative, maybe we can talk about what you are trying to do in our public slack with the rest of our team: https://join.slack.com/t/triggermesh-community/shared_invite/zt-1kngevosm-MY7kqn9h6bT08hWh8PeltA
