### ISSUE TITLE
AWSEventBridgeSource - Error getting current targets for rule

### ISSUE THREAD

**Issue by ziazek** [triggermesh/triggermesh#1306]
Seeing this error when creating a new AWSEventBridgeSource

> Error getting current targets for rule "rule/io_triggermesh_awseventbridgesources-3021178537": ValidationException: 1 validation error detected: Value 'rule/io_triggermesh_awseventbridgesources-3021178537' at 'rule' failed to satisfy constraint: Member must satisfy regular expression pattern: [\.\-_A-Za-z0-9]+

I was able to replicate the error message by running `aws events list-targets-by-rule --rule "rule/io_triggermesh_awseventbridgesources-3021178537"`.

The error message went away when running `aws events list-targets-by-rule --rule "io_triggermesh_awseventbridgesources-3021178537"`, which suggests that the "rule/" at the start of the string is the cause.

**Comment by sebgoa** [comment]
thanks for reporting the issue we will look into it.

Are you using `tmctl` or the kubernetes manifests ?

**Comment by sebgoa** [comment]
Can you try with an event-bus arn that is not the default event-bus ?

**Comment by ziazek** [comment]
I'm using Kubernetes manifests. I'm trying to get S3 object notifications via EventBridge, so it doesn't make sense to use a custom event bus in this case.

**Comment by sebgoa** [comment]
I am re-opening this while I test the nightly build. I will report back

**Comment by sebgoa** [comment]
Hi @ziazek this is now fixed in our v1.23.2 release.

Please give it a try and let me know that it works for you, I will close the issue after that.

I tested it with our CLI `tmctl` and it worked like a charm.

**Comment by ziazek** [comment]
Hi @sebgoa apologies for the late reply - we've decided to use TriggerMesh's SQS source (on AWS, S3 to SNS, fanout to SQS) to accomplish the task. I'll try to find time in the coming week to try this fix and update again, but please go ahead to close the issue.
