### ISSUE TITLE
Trigger the artifacts build on dev branches 

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/triggermesh#1351]
Sometimes we need to have the build [artifacts](https://app.circleci.com/pipelines/github/triggermesh/triggermesh/3740/workflows/cf956b41-3cb9-4da8-875d-e7abc37a93d6/jobs/10371/artifacts) before merging dev branch to the main to be able to run manual tests. Would be nice if we could post CI command in the PRs comments that would trigger build and publish jobs. Now it happens only on the "main" branch.

**Comment by sameersbn** [comment]
Addressed in #1362
