### ISSUE TITLE
[Request] Add Reconciling ServiceAccounts to 1.24 Release

### ISSUE THREAD

**Issue by coding-trees** [triggermesh/triggermesh#1363]
Hi,

I noticed that recently an improvement was made to ServiceAccount reconciliation as part of this PR https://github.com/triggermesh/triggermesh/pull/1354

It seems like it was merged and released as part of the https://github.com/triggermesh/triggermesh/releases/tag/v1.21.2 release.

I was wondering if those ServiceAccount reconciliation improvements could also be added to the v1.24 release, there are items int he 1.24 release that would be helpful to use but my company has an internal image repository so we have a need to use serviceAccounts with our own `imagePullSecrets` 

Thank You.

**Comment by sameersbn** [comment]
Thanks for your feedback @coding-trees 
The change is already in-place and scheduled for release with the next patch release.  I'll check with the team and get back to you soon.

**Comment by sameersbn** [comment]
[v1.24.1](https://github.com/triggermesh/triggermesh/releases/tag/v1.24.1) has been released with this update

**Comment by sebgoa** [comment]
@coding-trees Sameer just cut v1.24.1 with this patch for you. Let us know how this works out, feel free to re-open.

**Comment by coding-trees** [comment]
Yes, that worked out great. Thanks for the prompt response and assistance!
