### ISSUE TITLE
AzureQueueStorageSource - Configurable Timeout Support

### ISSUE THREAD

**Issue by sanjay-motorq** [triggermesh/triggermesh#1382]
The azure storage queue source in Triggermesh currently has a [20 second timeout](https://github.com/triggermesh/triggermesh/blob/main/pkg/sources/adapter/azurequeuestoragesource/adapter.go#L148). Azure queue however, supports message level timeouts upto 7 days.
An option to configure the default timeout would definitely help.

I had a use case where I needed a longer timeout. Ended up writing my own pollers since the timeout was not configurable in 
Triggermesh.

**Comment by FranBarrera** [comment]
@sanjay-motorq The feature is currently only available on the main branch. Deployment manifests can be found here: https://github.com/triggermesh/triggermesh/suites/11940794398/artifacts/625887399 Those are development artifacts. You can safely deploy them on top of your existing TriggerMesh installation in your test environment, but the feature will only become officially available in the next release of TriggerMesh.
