### ISSUE TITLE
Object prefix filter is not supported in Google Cloud Storage Source

### ISSUE THREAD

**Issue by roeizavida** [triggermesh/triggermesh#1421]
When creating a `GoogleCloudStorageSource` resource, the `--object-prefix` flag of `gcloud storage buckets notifications create` command is not supported.
It looks like because it is not available in the CRD, the controller tries to recreate the notification configuration without this field.
When creating the notification without it, the source is working.
Is there another way to filter the events from the bucket?

**Comment by roeizavida** [comment]
Actually by looking at the source code, it seems like a small change so I have opened a PR for it (#1422).

**Comment by tzununbekov** [comment]
#1422 fix is merged. Thank you @roeizavida
