### ISSUE TITLE
Support authentication with AWS IAM Roles Anywhere | AWS_SESSION_TOKEN support

### ISSUE THREAD

**Issue by RealArtemiy** [triggermesh/triggermesh#1440]
## Description
AWS session token support

## Additional context
Referring to the documentation - nothing about AWS_SESSION_TOKEN support

Example usage: on-premise cluster without static AWS credentials, temporary credentials (AWS access and secret keys + session token) are being generated by AWS roles anywhere feature
https://docs.aws.amazon.com/rolesanywhere/latest/userguide/authentication-create-session.html

Does trigger mesh support session token, if so - could you please add this to documentation?

**Comment by jmcx** [comment]
@RealArtemiy we've moved this to the correct repo, we'll start having a look at it. 

I'll ping you on LinkedIn, it would be great if we could jump on a quick call to get to know you a bit!

**Comment by jmcx** [comment]
Ok I couldn't add you on linkedIn, here is me: https://www.linkedin.com/in/jmcx/ or jonathan@triggermesh.com, would love to jump on a quick intro call ! Thanks

**Comment by sebgoa** [comment]
@RealArtemiy could you check https://github.com/triggermesh/triggermesh/pull/1446 and tell us if that would work for you ?

**Comment by tzununbekov** [comment]
@RealArtemiy to make sure that you have the right versions deployed, could you use our dev manifests from [here](http://github.com/triggermesh/triggermesh/suites/13595480280/artifacts/749297615) and repeat the test?

**Comment by RealArtemiy** [comment]
Hello,
```
$ kubectl apply -f https://github.com/triggermesh/triggermesh/releases/download/v1.25.1/triggermesh-crds.yaml
$ kubectl apply -f https://github.com/triggermesh/triggermesh/releases/download/v1.25.1/triggermesh.yaml
$ aws sts get-session-token 
```
copied AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN

Created a kubernetes manifest

```
apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""
```
and applied
`kubectl apply -f secret.yml`

tm.yml is here https://github.com/triggermesh/triggermesh/issues/1440#issuecomment-1588919638

creating an object in s3 bucket and checking events:
 `kubectl get events --sort-by='.lastTimestamp'`

```
42s         Warning   FailedSubscribe                awss3source/triggermesh-s3-source                                            (combined from similar events): Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....
```

am I missing something ?

**Comment by tzununbekov** [comment]
> ```
> $ kubectl apply -f https://github.com/triggermesh/triggermesh/releases/download/v1.25.1/triggermesh-crds.yaml
> $ kubectl apply -f https://github.com/triggermesh/triggermesh/releases/download/v1.25.1/triggermesh.yaml
> $ aws sts get-session-token 
> ```

Patch version v1.25.1 does not include session token support, please deploy the dev manifest and repeat the test:
https://github.com/triggermesh/triggermesh/suites/13595480280/artifacts/749297615

**Comment by RealArtemiy** [comment]
<details>
  <summary> kubectl get ev</summary>

```

12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....

12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....

12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....

12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....

12m         Normal    LatestReadyUpdate   configuration/awssqstarget-triggermesh-aws-sqs                            LatestReadyRevisionName updated to "awssqstarget-triggermesh-aws-sqs-00003"

12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....

12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....

12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....

12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....

12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....
```
</details>
@tzununbekov 
Is there anything else I can check?

**Comment by tzununbekov** [comment]
> kubectl get ev
> ```
> 
> 12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....
> 
> 12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....
> 
> 12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....
> 
> 12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....
> 
> 12m         Normal    LatestReadyUpdate   configuration/awssqstarget-triggermesh-aws-sqs                            LatestReadyRevisionName updated to "awssqstarget-triggermesh-aws-sqs-00003"
> 
> 12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....
> 
> 12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....
> 
> 12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....
> 
> 12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....
> 
> 12m         Warning   FailedSubscribe     awss3source/triggermesh-s3-source                                         Error creating AWS API clients: determining bucket's owner: getting ID of caller: InvalidClientTokenId: The security token included in the request is invalid....
> ```
> 
> @tzununbekov Is there anything else I can check?

These events are reporting the issues with the `awss3source/triggermesh-s3-source` object, but I don't see it in your manifests. There is also one line that marks your `awssqstarget` as "ready" and this one I see in the manifest you shared: 
```
12m         Normal    LatestReadyUpdate   configuration/awssqstarget-triggermesh-aws-sqs                            LatestReadyRevisionName updated to "awssqstarget-triggermesh-aws-sqs-00003"
```
Could you clarify which component are you testing - S3 source or SQS target? `kubectl describe` output for this object also would be useful.

**Comment by tzununbekov** [comment]
For the record: after debugging session, this [PR](https://github.com/triggermesh/triggermesh/pull/1455) was created. Further discussion moved to Slack.

**Comment by jmcx** [comment]
Docs added here: https://github.com/triggermesh/docs/pull/394
