### ISSUE TITLE
CloudEventsTarget spec documentation does not comply with the crd

### ISSUE THREAD

**Issue by apenen** [triggermesh/triggermesh#1443]
Documentation:
![image](https://github.com/triggermesh/triggermesh/assets/9284027/3a444438-f4a8-4872-a15d-999e057b0f4b)

K8s explaining crd:
![image](https://github.com/triggermesh/triggermesh/assets/9284027/b9ec4616-b83c-457b-ae03-715e975147f9)

Should be added a /path for listen to events?

**Comment by jmcx** [comment]
Good catch! Maybe @odacremolbap can have a look?

**Comment by odacremolbap** [comment]
Thanks @apenen 

The CRD was not updated with the `path` change.
Will push a fix in the next minutes.
