### ISSUE TITLE
 GCP Cloud Services - Custom KSA Names in Targets

### ISSUE THREAD

**Issue by apenen** [triggermesh/triggermesh#1463]
Hi!

You could make the google cloud targets also have the configuration to use KSA, resolved in #1372?

Thanks!

**Comment by jmcx** [comment]
Hi @apenen, thanks for raising this issue. Sounds like a logical improvement, we'll keep it on our radar. 

Feel free to [join our Slack](https://join.slack.com/t/triggermesh-community/shared_invite/zt-1kngevosm-MY7kqn9h6bT08hWh8PeltA) if you haven't already, we'd love to know more about your use case.

**Comment by apenen** [comment]
Thanks!
