### ISSUE TITLE
Feature Request: Add built-in transformation for avro to json

### ISSUE THREAD

**Issue by snuggie12** [triggermesh/triggermesh#1492]
I noticed there are some built in transformations such as xml to json. avro schemas are pretty commonly used. I was wondering if you all would consider adding that as a built-in transformation.

**Comment by ynovytskyy** [comment]
Sounds like it could cover common integration use case:
PubSub (or other source) message with AVRO payload -> broker with AVRO-to-JSON -> HTTP target pointing to where JSON is expected as REST body/input

Looking at https://docs.triggermesh.io/1.26/transformation/other/xslttransformation/, AVRO-to-JSON could be quite similar. It requires 2 pieces of information:  
- payload - AVRO payload (similar to XML input in xslttransformation) comming with each message
- metadata - AVRO schema (similar to XSLT in xslttransformation) to able to parse payload and produce JSON

**Comment by sebgoa** [comment]
When you can confirm that you are using triggermesh and that we can use your logo we will address this issue at no cost.
thank you
