### ISSUE TITLE
Change broker's port name for Service and Pod from httpce to http

### ISSUE THREAD

**Issue by xbglowx** [triggermesh/triggermesh#1493]
This doesn't play nice with istio, since istio is expecting `<protocol>[-<suffix>]` and `httpce` and `metrics` are not a valid protocol. Another option would be to leverage `appProtocol`.

https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

**Comment by sebgoa** [comment]
When you can confirm that you are using triggermesh and that we can use your logo we will address this issue at no cost.
thank you
