### ISSUE TITLE
Info Request: I'm a little confused. Is the project ending?

### ISSUE THREAD

**Issue by mannu-silva** [triggermesh/triggermesh#1519]
I didn't see anything written on the front page of Triggermesh or on the git project. But when I joined Slack, this is what I found from Sebastien Goasgen:

"Dear TriggerMesh community, over the last 3-1/2 years we have tried to build a cloud-native platform for event driven applications. Despite your adoption and feedback we have not reached the point of having a sustainable business. Time has come for us to make a hard decision. We will shutdown the company before the end of the year. We are very proud of what we have built and we thank you for using our software to solve your company needs, we hope that it was useful for you all. If you have any questions please reach out to me directly ( [sebgoa@triggermesh.com](mailto:sebgoa@triggermesh.com)) . Sebastien (CEO and Co-founder) on behalf  of the TriggerMesh team."

with that, what happens to this project?  Thank you.

**Comment by sebgoa** [comment]
Hi, the company is shutting down as I wrote. What happens to this software time will tell.

If you want paid support you can always contact me.
