### ISSUE TITLE
Create XML to JSON transformation

### ISSUE THREAD

**Issue by odacremolbap** [triggermesh/triggermesh#303]
XML to JSON transformation was worked on in a hack-ish way at InfraJS (being deprecated).

https://github.com/triggermesh/triggermesh/blob/22c6a5877a3934f802623848f89be4d057790953/pkg/targets/adapter/infratarget/vm/javascript/javascript_vm.go#L94-L102

XML cannot match one to one with JSON, we should give users the chance to configure how attributes are rendered into JSON and provide documentation on it. For reference, InfraJS does not allow configuring attributes rendering, but documents how it works:

https://docs.triggermesh.io/cloud/targets/infrajs/#xml-support

**Comment by JeffNeff** [comment]
Names for the XML to JSON transformation/target? Having issues deciding on one:
`XMLToJSONTarget`
`XMLToJSONTransformation` (if so then where should this live?)
`XMLToJSON`


I started building it in the targets folder named `XMLToJSONTarget` but I just want to double-check that I am headed in the right direction with the name and its location.

**Comment by antoineco** [comment]
My 2c: a target is a final destination for any given event, but this one is not. It's an intermediate hop just like a filter, splitter, or bumblebee transformation.
I think it should live in the same API group as bumblebee.

**Comment by odacremolbap** [comment]
What Antoine said: https://github.com/triggermesh/misc/issues/205

**Comment by JeffNeff** [comment]
ok. So then should I add a new component there, or extend  `transformation` to accept XML and return JSON? Currently, we just [check that the incoming content type is JSON ](https://github.com/triggermesh/triggermesh/blob/bd69609b0c5d45a2a5c71f72239bc73d6e6904c5/pkg/transformation/pipeline/handler.go#L106) and reject anything else.

**Comment by antoineco** [comment]
@JeffNeff just create a new type, no need to overload existing components and the purpose is completely different here.

**Comment by antoineco** [comment]
I would love to see a document showcasing the scope and design of this component: what it does, how it does it, what edge cases must be included in tests, ...

Without clear expectations, the PR will remain in Draft limbo with a lot of review cycles, add a high chance to end up being closed.

Let's agree on what needs to be done first, and send a PR once _all_ boxes have been checked. Partial PRs are impossible to review, especially when they include >10 commits.

@odacremolbap @JeffNeff @sebgoa

**Comment by JeffNeff** [comment]
### XML to JSON Transformation v1 

## What it Does
An easy to use service that accepts Cloudevents with XML data as the payload and returns a new event containing an equivalent in JSON as string values. 

 ## How it does it
 By utilizing the Go package `github.com/basgys/goxml2json` we can accept XML data and return JSON. 
 
 Below is an example adapter demonstrating the use of the package
 
```
package xmltojsontransformation

import (
	"context"
	"strings"

	"go.uber.org/zap"

	xj "github.com/basgys/goxml2json"
	cloudevents "github.com/cloudevents/sdk-go/v2"
	pkgadapter "knative.dev/eventing/pkg/adapter/v2"
	"knative.dev/pkg/logging"

	targetce "github.com/triggermesh/triggermesh/pkg/targets/adapter/cloudevents"
)

// EnvAccessorCtor for configuration parameters
func EnvAccessorCtor() pkgadapter.EnvConfigAccessor {
	return &envAccessor{}
}

type envAccessor struct {
	pkgadapter.EnvConfig

	// BridgeIdentifier is the name of the bridge workflow this target is part of
	BridgeIdentifier string `envconfig:"EVENTS_BRIDGE_IDENTIFIER"`
	// CloudEvents responses parametrization
	CloudEventPayloadPolicy string `envconfig:"EVENTS_PAYLOAD_POLICY" default:"error"`
}

// NewTarget adapter implementation
func NewTarget(ctx context.Context, envAcc pkgadapter.EnvConfigAccessor, ceClient cloudevents.Client) pkgadapter.Adapter {
	env := envAcc.(*envAccessor)
	logger := logging.FromContext(ctx)

	replier, err := targetce.New(env.Component, logger.Named("replier"),
		targetce.ReplierWithStatefulHeaders(env.BridgeIdentifier),
		targetce.ReplierWithStaticResponseType("io.triggermesh.xmltojsontarget.response"),
		targetce.ReplierWithPayloadPolicy(targetce.PayloadPolicy(env.CloudEventPayloadPolicy)))
	if err != nil {
		logger.Panicf("Error creating CloudEvents replier: %v", err)
	}

	return &adapter{

		replier:  replier,
		ceClient: ceClient,
		logger:   logger,
	}
}

var _ pkgadapter.Adapter = (*adapter)(nil)

type adapter struct {
	replier  *targetce.Replier
	ceClient cloudevents.Client
	logger   *zap.SugaredLogger
}

// Returns if stopCh is closed or Send() returns an error.
func (a *adapter) Start(ctx context.Context) error {
	a.logger.Info("Starting XMLtoJSONTarget Adapter")
	return a.ceClient.StartReceiver(ctx, a.dispatch)
}

func (a *adapter) dispatch(ctx context.Context, event cloudevents.Event) (*cloudevents.Event, cloudevents.Result) {
	xml := strings.NewReader(string(event.Data()))
	json, err := xj.Convert(xml)
	if err != nil {
		return a.replier.Error(&event, targetce.ErrorCodeAdapterProcess, err, nil)
	}
	event.SetType("io.triggermesh.xmltojsontarget.response")
	event.SetData("appllication/json", json)
	return &event, cloudevents.ResultACK
}

``` 

# Edge Cases to be Included in Tests

**Comment by JeffNeff** [comment]
I could use some help with `Edge Cases to be Included in Tests`. I'm not positive what should go under this section ;/ .

**Comment by antoineco** [comment]
@JeffNeff I think you could shorten your description by going straight to the critical piece of information and skipping this long code snippet.

The critical piece of information is that you will rely on `github.com/basgys/goxml2json` to perform the conversion. The rest is just boilerplate.

This also covers the testing angle, since we can assume that the third-party library has sufficient tests.

Can we reason about the event type though? If I receive `github.push` in, it's a bit weird to get `io.triggermesh.xmltojsontarget.response` out. IMO the event type is still `github.push` in that case, only the **encoding** has changed.

**Comment by JeffNeff** [comment]
@antoineco Okay! Totally agree about the Event type. I do have a question on the Source.. the above snippet is passing along the original source. Do you agree with this design choice? Or should the Source be changed?

**Comment by JeffNeff** [comment]
@antoineco actually... thinking it... if we keep the same event type, that may make it a bit difficult to configure the trigger filtering. Would it not?

**Comment by JeffNeff** [comment]
What if we were to append `.json` to the incoming event type? 

So, we get `github.push` and return `github.push.json`

**Comment by antoineco** [comment]
If we only touch the encoding, I think everything except the CloudEvent's [`datacontentype`](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#datacontenttype) (it's automatically populated by `ce.SetData()`) should be left untouched.

`json` is not a type, it's the content type (encoding). So no, I wouldn't touch the type.

**Comment by JeffNeff** [comment]
ok so than just for giggles and wonders... What would you choose to filter by for the newly generated event?

**Comment by antoineco** [comment]
About content filtering, it's probably a poor design choice to mix identical payloads with different encodings inside the same broker anyway, because the consumers are unlikely to be the same. Regardless, we shouldn't be making the decision for the user. We should remain as neutral as possible in the way we handle data, and appending arbitrary strings to the original event attributes.

With that being said, if you have such case, you can always filter on `type` + `datacontentype`.

**Comment by antoineco** [comment]
Everything that sits between a broker and an event target is an adapter / data converter.
Given a canonical event, I should be able to pass it again to the adapter and get the same output. No need to store that event back into a Broker, because it's not the source of truth.
