### ISSUE TITLE
SQS Source Silently Fails Provided Improper Authentication Credentials

### ISSUE THREAD

**Issue by JeffNeff** [triggermesh/triggermesh#312]
When deploying or running an AWS SQS Source, if one is to provide improper credentials, the Source will report that it has been configured properly and is listening to the Queue. However, no events will actually be created or sent and no error messages are created to notify the user that improper credentials were provided.

**Comment by antoineco** [comment]
When I provide invalid credentials, this call fails and the adapter exits with an error:

https://github.com/triggermesh/triggermesh/blob/e110e986f4ce357567f116aec5c8c2ab6c19fb66/pkg/sources/adapter/awssqssource/adapter.go#L173

Could you please provide more details on how to reproduce?

**Comment by JeffNeff** [comment]
Let me try to reproduce!

**Comment by JeffNeff** [comment]
There are actually errors that appear if you `kubectl  get events`.. i just did not know about this until a few days ago. closing the issue
