### ISSUE TITLE
Add option to base64 decrypt AWSKinesisSource Data field 

### ISSUE THREAD

**Issue by cparlette** [triggermesh/triggermesh#320]
The 'Data' field in AWS Kinesis is always base64 encoded.  Users can currently create a transform in TriggerMesh to decrypt, but adding a flag to automatically decrypt the data would make Kinesis easier to use as a source.

According to https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecord.html#API_PutRecord_RequestSyntax , the Data field is always base64.

**Comment by antoineco** [comment]
Nice catch!

There could be reasons to keep the data encoded if it's binary, but we should decode _whenever possible_ like we do in the sources for Azure Event Hubs and Google Pub/Sub.
