### ISSUE TITLE
Create a component documentation template

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/triggermesh#336]
We should standardise on how we document each component. For example a template could be:

* A brief describing the component
* Usage
* API ?
* Schema
* Sample events

**Comment by tzununbekov** [comment]
I vote for the following:

1. Re-organize hierarchy in [docs](https://github.com/triggermesh/docs) to make it a bit more formal,
2. Move [docs](https://github.com/triggermesh/triggermesh/tree/main/docs) from this repo to the `triggermesh/docs`,
3. This repo can be the source for the generated references and dev docs that are not exposed in docs.triggermesh.com.
