### ISSUE TITLE
Spawn and terminate receivers dynamically

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#37]
We should spawn and terminate receivers dynamically based on the current amount of messages being processed (internal queue lengths should be a good indicator of this) to optimize costs generated by `ReceiveMessage` API requests (https://aws.amazon.com/sqs/pricing/).

**Comment by marvin-w** [comment]
Is there an effort to autoscale the receivers based on the available messages in the queue?

Similar projects/efforts include:

https://github.com/sideshowbandana/k8s-sqs-autoscaler
https://github.com/Wattpad/kube-sqs-autoscaler/issues/7

**Comment by antoineco** [comment]
@marvin-w relying on the `ApproximateNumberOfMessages` attribute, like these projects do, could be one way to auto-scale the receivers indeed.

**Comment by marvin-w** [comment]
There are a lot of "solutions" to this, but I'm not sure which one would be a good one.

1. It would be nice to have this metric as a custom metric in k8s and let e.g. an HPA handle the scaling.
2. A custom operator that has a CRD to allow scaling mutliple deployments based on a given queue/s.
3. Built it straight into the receivers in triggermesh? (Not really sure if this is viable or doable)

Context: We are currently searching for a way to process more than 10.000 Messages / second via a SQS Standard Queue. Queues size will vary of course so autoscaling should be there.

**Comment by antoineco** [comment]
@marvin-w oh, you're talking about scaling the instances of the receive adapter. What I had in mind was a mechanism _inside_ the receive adapter to scale down the number of API calls to AWS when the queue is already drained in order to save costs.

We have an old issue about auto-scaling receive adapters at https://github.com/triggermesh/aws-event-sources/issues/230.
My own conclusion was that everyone is likely to approach this problem differently based on what is available to them, so I wouldn't "bake" it inside TriggerMesh.

With that being said, if you already have a standard Prometheus stack deployed in your cluster, and expose its metrics using the Kubernetes metrics API, you will find out that you can get the current depth of the internal processing queue, as a percentage of its total capacity, using the following Prometheus query:

```promql
(
 
 awssqssource_message_enqueued_process_count{namespace_name="my-ns", name="my-sqs"}
  -
 
 awssqssource_message_dequeued_process_count{namespace_name="my-ns", name="my-sqs"}
)

/

awssqssource_queue_capacity_process{namespace_name="my-ns", name="my-sqs"}
```

(You can see an example of dashboard that uses this exact metric in #39)

Under load, this internal queue will fill up (which, as a side effect, applies some backpressure to the concurrent SQS receiving processes), so you can quite easily scale on a certain threshold.
For example, scale if the queue depth is > 80%, until the depth decreases, which would indicate that messages are being processed faster than the SQS queue is filling.
