### ISSUE TITLE
Migrate to new `Azure/azure-sdk-for-go` resource management packages

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#385]
Microsoft recommends using the new subpackages of `Azure/azure-sdk-for-go/sdk/resourcemanager` to manage resources on Azure: https://github.com/Azure/azure-sdk-for-go/tree/v60.3.0#management-new-releases

**Comment by FranBarrera** [comment]
Closing this one, it was fixed with the last [PR](https://github.com/triggermesh/triggermesh/pull/1398)
