### ISSUE TITLE
Create copyright header check script

### ISSUE THREAD

**Issue by cab105** [triggermesh/triggermesh#424]
Will need a commit hook/github action to verify the copyright header corresponds to what is expected for the project including ensuring the copyright year is updated.

**Comment by antoineco** [comment]
We already do, unless I misunderstood?

https://github.com/triggermesh/triggermesh/blob/67e8d5c90b172de8187ca9ee46f6ef0bb7f30f3a/.github/workflows/licenses.yaml#L39

https://github.com/triggermesh/triggermesh/blob/67e8d5c90b172de8187ca9ee46f6ef0bb7f30f3a/.github/workflows/config/reviewdog.yaml#L6-L10

**Comment by cab105** [comment]
That's what I thought as well, but believe I let one slide that didn't get caught. Will confirm with my next push, and if I'm wrong, then will close this out.

**Comment by antoineco** [comment]
Just to clarify, the year is ignored as long as the content of the header is correct, in case you were wondering why it didn't complain that you didn't bump the year after editing a file.

There is no written requirement to bump the year so everybody does how they please. Kubernetes (maybe CNCF? Can't remember) explicitly says the year shouldn't be modified, but I have literally zero idea whether that matters.

If we really want to enforce that the year is bumped in case a file is modified in year 202x, then I agree that we need to ask Git for the last modification timestamp, etc.

**Comment by antoineco** [comment]
Bonus question: what do we do with files that were relocated from other repos (test-infra comes to mind) but not modified. What should the year be for these files?

**Comment by cab105** [comment]
Thanks for that clarification, and it does matter when it comes to when copyright expires as some countries and organizations use that to determine when ownership should expire.

**Comment by cab105** [comment]
From prior experience, the year is updated upon creation/modification. Don't believe it changes when it is moved unaltered.

**Comment by cab105** [comment]
If we do want to enforce the year, than a simple grep for the copyright line to ensure it matches `Copyright (c) TriggerMesh 'date %Y'.

**Comment by antoineco** [comment]
But how does the script know that the file was moved unaltered if it only has access to the modification timestamp? (I'm just being picky because I try to understand the ramifications of such enforcement on developers' work flow)

**Comment by antoineco** [comment]
(I didn't mean we shouldn't do it!)

**Comment by cab105** [comment]
The script wouldn't know the unaltered state, but the human reviewers would. In this case, the copyright check would be against files modified and not files added. For the files added we will see and review the full file, and then can point out when something is amiss.
