### ISSUE TITLE
Remove `/transformation` Folder and Migrate Contents to `/flow`

### ISSUE THREAD

**Issue by JeffNeff** [triggermesh/triggermesh#454]
The `transformation` folder is a bit of an eye-sore in my opinion. I don't understand why we have it isolated away from the other components. Would anyone be against the migration of its contents with the rest of the transformation bits under `flow`?

**Comment by JeffNeff** [comment]
@tzununbekov @odacremolbap @antoineco @cab105

**Comment by tzununbekov** [comment]
[PR](https://github.com/triggermesh/triggermesh/pull/353) is waiting for the review
