### ISSUE TITLE
High CPU usage in AWS AMI

### ISSUE THREAD

**Issue by sameersbn** [triggermesh/triggermesh#488]
I am noticing very high CPU utilization in the AMI to deploy TM on EC2. In a very short period the CPU utilization is so high that it makes the Kubernetes node completely unresponsive.

**Comment by sameersbn** [comment]
I am carry out some tests to check where the load is coming from.

**Comment by antoineco** [comment]
@sameersbn can we declare bankruptcy on this issue?

**Comment by sameersbn** [comment]
closing!

**Comment by jerrychong25** [comment]
> I am carry out some tests to check where the load is coming from.

Hi @sameersbn ,

Recently I faced similar issue in Amazon Machine Image (AMI) too, mind to share what steps u took to finding the root cause?

Thanks.

**Comment by sameersbn** [comment]
@jerrychong25 in our case it was to do with the k3s server. Over a period of time the performance of the single node k3s cluster was degrading drastically. We were not able to resolve the issue and since our AMI is intended for demo or getting started purposes, we didn't want to invest too much effort to find and resolve the issue.

**Comment by jerrychong25** [comment]
> @jerrychong25 in our case it was to do with the k3s server. Over a period of time the performance of the single node k3s cluster was degrading drastically. We were not able to resolve the issue and since our AMI is intended for demo or getting started purposes, we didn't want to invest too much effort to find and resolve the issue.

@sameersbn I see, thanks for great sharing!
