### ISSUE TITLE
Create a test helper for intercepting and asserting event responses

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#536]
I suggest that we implement a helper inside the E2E test framework for automatically deploying a Knative Eventing topology that would allow us to intercept and assert event responses from any Addressable.

The helper would deploy, and auto-wire, the 3 components below:
- a `Channel`, which acts as the entry point for routing CloudEvents to the Addressable
- an event-display `Deployment` (+k8s `Service` in front of it), which receives responses
- a `Subscription`, which performs the actual routing of incoming events to the Addressable, and routing of responses to event-display

The helper returns the following values:
- the address of the `Channel` (or a reference we can use to read the address), to be able to send events to it
- a reference to the event-display `Deployment`, so we can read the events it received

![E2E reply analysis drawio](https://user-images.githubusercontent.com/3299086/152018056-827781ab-1740-4a8c-b76a-2b6d7be14aca.png)

**Comment by JeffNeff** [comment]
Rockstar! +1
