### ISSUE TITLE
Synchronous flows based on the Webhook source

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/triggermesh#542]
I've been working on the various demo integration flows that involved the Synchronizer component; these flows are meant to return data in responses back to the client. Our Webhook source was chosen as the simple event gateway to pass the client requests into the system. After some tests, I've figured out that the source does not return any data, [only statuses](https://github.com/triggermesh/triggermesh/blob/4ca954341093d68e9d08a56ccb617744d563a7ea/pkg/sources/adapter/webhooksource/webhook.go#L141).

Since this component is placed on the border between the regular HTTP client systems and CloudEvents based platforms, can we consider extending its behavior a bit out of CE framework boundaries and making it handle data as well as statuses? Otherwise, having HTTP webhooks that are limited to status responses only is a strong limiting factor, isn't it?

**Comment by antoineco** [comment]
@sebgoa and people who follow that issue: since we are currently discussing this topic at a larger scale, would it be fair to close this issue?
