### ISSUE TITLE
Include standard Kubernetes labels in all Pods managed by TriggerMesh

### ISSUE THREAD

**Issue by antoineco** [triggermesh/triggermesh#589]
Currently, only sources and routers apply the set of [recommended Kubernetes labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) to the objets they create (Deployments, Knative Services, and nested Pod templates).

https://github.com/triggermesh/triggermesh/blob/3fa77e61e7540ff260448433483619b8ffbcaae4/pkg/sources/reconciler/common/adapter.go#L247-L256

It would be easier to monitor TriggerMesh components if we had a set of labels present by default on all Pods managed by TriggerMesh. I'm thinking about `part-of: triggermesh` and `name: <component type>` especially.

**Comment by antoineco** [comment]
Here is what I'm expecting every component to include (both the top-level object and the lower-level Pods):

```jsonc
{
  "app.kubernetes.io/part-of": "triggermesh",                // always "triggermesh"
  "app.kubernetes.io/managed-by": "triggermesh-controller",  // always "triggermesh-controller"
  "app.kubernetes.io/component": "adapter",                  // "adapter" in most cases, unless CR needs multiple components
  "app.kubernetes.io/name": "ibmmqsource",                   // Kubernetes kind of the TriggerMesh component
  "app.kubernetes.io/instance": "myqueue",                   // metadata.name of the resource instance
}
```

- The first two are mostly informative. They help an administrator understand the origin of an application.

- `component` is rather useless in our case, because each CR currently translates to only one component called "adapter". By that, I mean that we don't have components that deploy additional services, such as Redis or Postgres, along their adapter (but we could). Regardless, I think it's good to include it because Kubernetes recommends it.

- `name` is not to be mixed up with the CR's name. Kubernetes describes it as the **name of the application**. So if the application is an event source fot IBM MQ, the app's name should say that.

- `instance` should be unique for a given instance of the application. Kubernetes names are unique within a namespace, so I think using the CR's name here is a fairly natural choice.

**Comment by antoineco** [comment]
An example of component that does not satisfy this pattern:

```json
{
  "app.kubernetes.io/component": "adapter",
  "app.kubernetes.io/instance": "mq-input-channel",
  "app.kubernetes.io/managed-by": "knative-targets-controller",
  "app.kubernetes.io/name": "ibmmqtarget",
  "app.kubernetes.io/part-of": "knative-targets"
}
```

-> `knative-targets` isn't our project's name. It doesn't even mention "triggermesh".

Another example:

```json
{
  "app.kubernetes.io/component": "adapter",
  "app.kubernetes.io/instance": "ibm-mq",
  "app.kubernetes.io/managed-by": "triggermesh-controller",
  "app.kubernetes.io/name": "synchronizer",
  "app.kubernetes.io/part-of": "triggermesh-flow"
}
```

-> adding `-flow` to `triggermesh` is deliberate and only extends the number of values `part-of` can have. Users should be able to rely on a single value. The API group `"flow"` is already part of `apiVersion`.

**Comment by tzununbekov** [comment]
@antoineco I can take care of the Flow and Extensions API groups, and some of the targets, if you don't mind

**Comment by antoineco** [comment]
Sure, unassigning myself 👍
