### ISSUE TITLE
Adapter parameters overriding

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/triggermesh#705]
The idea of introducing the mechanism for low-level adapter parameters overriding is inspired by the following cases:

**Knative service labels:**
- Synchronizer issue. Currently, we cannot utilize Synchronizer functionality without a custom connection link between external systems and Triggermesh components (e.g. Kong gateway with CE plugin or Webhook source with a custom CE client),
- It is happening quite often that we need to have an access to the component's endpoint for direct interaction with the adapter for debugging purposes or to use it as a standalone service.

Setting Knative service network visibility scope label would help resolve these issues.

**Adapter's environment variables:**
- CE Overrides. Context attributes overrides are defined as a part of the sources spec but other components do not seem to have that ability, while there is no reason to limit it to the sources only,
- Delivery configuration. In bridges with multiple targets and different conditional routes, CE responses handling can become a very complex task and there are no chances we can have predefined, hardcoded delivery logic (errors, payloads, dls, etc.) in every component that would suit all possible scenarios.

These parameters are usually configurable through the adapter environment variables.

**Custom resources:**
- Extend adapter limits. Some adapters may require more compute resources for events processing tasks in the high load environments,
- Adding custom resources, such as secret mount or external volume may be something that we want to have as an opportunity in the future.

---

Would it make sense to work on the common solution for the described cases or should we solve the problems as they come, extending every particular component's spec one by one? If we go with the former, I see us implementing "adapter overridable" duck type that exposes meta and spec keys with the implementation depending on the adapter type.

**Comment by antoineco** [comment]
Do you have a first draft to suggest, just to kickstart some discussion?

Would that take the shape of a nested Go struct that's embeddable in all types' spec?

**Comment by tzununbekov** [comment]
I thought of starting with the simple structure to override the adapter's labels and envs. I'm not sure about the best way to expose overridable parameters: a predefined set of `labels`, `envs`, `resources`, etc. or just dump a raw corev1.Deployment spec there.

AWS SQS Source example with labels and envs overrides:

Reconcilable interface:
```diff
diff --git a/pkg/apis/common/v1alpha1/object_interfaces.go b/pkg/apis/common/v1alpha1/object_interfaces.go
index f8dd18e2..5be21a1f 100644
--- a/pkg/apis/common/v1alpha1/object_interfaces.go
+++ b/pkg/apis/common/v1alpha1/object_interfaces.go
@@ -39,6 +39,9 @@ type Reconcilable interface {

        // GetStatusManager returns a manager for the component's status.
        GetStatusManager() *StatusManager
+
+       // GetAdapterOverrides returns the adapter overrides.
+       GetAdapterOverrides() *AdapterOverrides
 }
```

Source structure:
```diff
diff --git a/pkg/apis/sources/v1alpha1/awssqs_types.go b/pkg/apis/sources/v1alpha1/awssqs_types.go
index a05e5af8..f59ff9d5 100644
--- a/pkg/apis/sources/v1alpha1/awssqs_types.go
+++ b/pkg/apis/sources/v1alpha1/awssqs_types.go
@@ -61,6 +61,10 @@ type AWSSQSSourceSpec struct {
        // Customizations of the AWS REST API endpoint.
        // +optional
        Endpoint *AWSEndpoint `json:"endpoint,omitempty"`
+
+       // Adapter spec overrides parameters.
+       // +optional
+       AdapterOverrides *v1alpha1.AdapterOverrides `json:"adapterOverrides,omitempty"`
 }
```

Reconciler:
```diff
diff --git a/pkg/reconciler/adapter.go b/pkg/reconciler/adapter.go
index 377f9acf..e34a27c3 100644
--- a/pkg/reconciler/adapter.go
+++ b/pkg/reconciler/adapter.go
@@ -146,6 +146,18 @@ func commonAdapterDeploymentOptions(rcl v1alpha1.Reconcilable) []resource.Object
                }
        }

+       overrides := rcl.GetAdapterOverrides()
+       if overrides == nil {
+               return objectOptions
+       }
+
+       for k, v := range overrides.Labels {
+               objectOptions = append(objectOptions, resource.Label(k, v))
+       }
+       for k, v := range overrides.Envs {
+               objectOptions = append(objectOptions, resource.EnvVar(k, v))
+       }
+
        return objectOptions
 }

@@ -221,6 +233,18 @@ func commonAdapterKnServiceOptions(rcl v1alpha1.Reconcilable) []resource.ObjectO
                }
        }

+       overrides := rcl.GetAdapterOverrides()
+       if overrides == nil {
+               return objectOptions
+       }
+
+       for k, v := range overrides.Labels {
+               objectOptions = append(objectOptions, resource.Label(k, v))
+       }
+       for k, v := range overrides.Envs {
+               objectOptions = append(objectOptions, resource.EnvVar(k, v))
+       }
+
        return objectOptions
 }
```

CRD:
```diff
diff --git a/config/300-awssqssource.yaml b/config/300-awssqssource.yaml
index 5dcf1d6a..fc02f726 100644
--- a/config/300-awssqssource.yaml
+++ b/config/300-awssqssource.yaml
@@ -167,6 +167,16 @@ spec:
                 oneOf:
                 - required: [ref]
                 - required: [uri]
+              adapterOverrides:
+                description: Kubernetes object parameters to apply on top of default adapter values.
+                type: object
+                properties:
+                  labels:
+                    type: object
+                    additionalProperties: true
+                  envs:
+                    type: object
+                    additionalProperties: true
             required:
             - arn
             - sink
```

**Comment by antoineco** [comment]
Maybe the example isn't very well chosen because if one wants to _temporarily_ set extra labels or environment variables for debugging purposes, they can already do that.
`DeepDerivative(desired, current)` ignores _extra_ elements in `current` as long as the rest of the slice or map is equal, so one can **add** an element using `kubectl edit` and the reconciler won't complain. (_Changing_ an existing element is a different story.)

But I totally understand the idea and I think that approach would be easy to implement the way you suggested 👍

Maybe we could refine the configurations we do want to support to make the API more intuitive.
Examples:

- If the goal is to let people expose some Ksvc components publicly, add a `adapterOverrides.visibility` attribute instead of expecting users to hack labels.
- If the goal is to support `ceOverrides` everywhere, embed `duck.SourceSpec` and [serialize spec.ceOverrides to JSON](https://github.com/triggermesh/triggermesh/blob/46464eca0ae139fb424fe4b4605e5969603bc281/pkg/sources/reconciler/googlecloudsourcerepositoriessource/adapter.go#L64) instead of expecting users to hack env vars.
- etc.

---

Regarding the handling of responses, I think the solution is to keep components as dumb as possible (use the `Replier` everywhere, "reply and forget") and leverage the fact that Knative Eventing's `Subscriptions` can route replies to an arbitrary destination.
TIL does that at the global level by interpolating a Channel+Subscription between literally every component in the Bridge, and setting the `deadLetterSink` in all these Subscriptions to a unique destination where _all_ responses are delivered.
We could re-use and extend that concept to not just errors but replies, at the level of the Bridge instead of per component, and act on responses in a central place.

**Comment by tzununbekov** [comment]
Alright, I'm all in for starting with the `adapterOverrides.visibility` attribute as it is really needed for Synchronizer CR not later than this week. I would also go with the `adapterOverrides.resources` as the next attribute to implement there. Regarding the `ceOverrides` - did you mean embedding `SourceSpec` right in the component's spec? If yes, are we fine with having source-specific spec in say target component? Wouldn't be an `adapterOverrides.ce` object with the type/source/etc. attributes a bit more in line with the common spec structure? Anyways, I'm okay with skipping the CE overrides for now.
___
Responses handling. Although it is not directly related to the adapter overrides I wanted to dump one thought that I had after experimenting with the synchronous bridges. Basically, I suggest that in _some_ cases we must extend components' dumbness over the whole bridge: 
If a source is an error-aware client and its connection with the target does not explicitly require adding complex middleware components, the bridge must hide its presence by skipping all error handling, retries, and DLS mechanisms. In general, I believe that this condition is mostly applicable to synchronous flows, but I cannot say that it won't be the case for some other integrations.
I'd start with preparing errors-handling patterns first while exposing these patterns as adapterOverride attributes is a pretty trivial task.

**Comment by antoineco** [comment]
> Regarding the `ceOverrides` - did you mean embedding `SourceSpec` right in the component's spec? If yes, are we fine with having source-specific spec in say target component? Wouldn't be an `adapterOverrides.ce` object with the type/source/etc. attributes a bit more in line with the common spec structure?

I think both are fine as long as they get serialized to the same JSON structure.

I suggested SourceSpec because, when you think about it, it contains only CEOverrides and Sink, which is what most of our components need. (In the case of targets, Sink can be empty, and that's OK)

**Comment by tzununbekov** [comment]
`AdapterOverrides` structure with the `public` switch and Resources Requirements added [here](https://github.com/triggermesh/triggermesh/blob/8b7545191d86f487140e2eef621b5bfd9fe78e76/pkg/apis/common/v1alpha1/types.go#L39-L45). Adapter configuration logic is [here](https://github.com/triggermesh/triggermesh/blob/8b7545191d86f487140e2eef621b5bfd9fe78e76/pkg/reconciler/adapter.go#L332-L338). All CRDs are populated with this structure, `AdapterConfigurable` interface is implemented by all components.
New issues may be created if additional parameters need to be overridden through this mechanism.
