### ISSUE TITLE
Toggle to indicate if the service URL should be internal or external

### ISSUE THREAD

**Issue by cab105** [triggermesh/triggermesh#767]
One of the things I've noticed with some of the TriggerMesh demos (both internal/external) is the reliance of running a pod inside the cluster, or rely on `kubectl port-forward` to inject data into a specific service.

What would be the risks of having this as a tunable to the source/targets/flows provided by the monorepo?

**Comment by antoineco** [comment]
I think this was done in #750

**Comment by cab105** [comment]
I thought that was more for the labels, but serves me right for not reviewing that PR.
