### ISSUE TITLE
Function CR: nil pointer access panic

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/triggermesh#770]
In the controller, we're accessing `ceOverrides` structure fields of the Function object without nil check:
https://github.com/triggermesh/triggermesh/blob/0787d1aa658d7e4ae7c2c425dde47b0b8f1c85d2/pkg/apis/extensions/v1alpha1/function_lifecycle.go#L58

Function may return CloudEvent with the Type and Source defined in the code, so making `ceOverrides` required in the CRD spec would not make much sense. We should probably return empty strings from `GetEventTypes()` and `AsEventSource()` if ceOverrides is not defined in the object.

**Comment by antoineco** [comment]
Oops, totally my fault.

In the refactoring to use the generic reconciler (#729) I did the right thing in `pkg/.../function/adapter.go`, but forgot to perform this check here.
