### ISSUE TITLE
Splitter does not send next cloud event in valid json format

### ISSUE THREAD

**Issue by nkreiger** [triggermesh/triggermesh#852]
Context Attributes,
  specversion: 1.0
  type: occurrence
  source: mock.group.split
  id: 202e26a7-3169-4227-95e8-13164d550109-0
  datacontenttype: application/json
Data,
  "{ \"id\":5, \"name\":\"foo\" }"

2022/05/09 18:57:00 Broadasting to 0 clients: {"data":"{ \"id\":5, \"name\":\"foo\" }","datacontenttype":"application/json","id":"202e26a7-3169-4227-95e8-13164d550109-0","source":"mock.group.split","specversion":"1.0","type":"occurrence"}
got Validation: valid

`"{ \"id\":5, \"name\":\"foo\" }"`

splitter correctly splits array, but then sends it in the json stringified form, so it cannot be consumed by more TM objects down the line...e.g. splitter -> transformation fails because they are not in json form

"this is from the docs demo"

**Comment by nkreiger** [comment]
the greyed out piece is what is actually looks like, github is formatting the other piece

**Comment by antoineco** [comment]
Indeed, we are doing the wrong thing by passing a raw string.

Here is what we should be doing instead: https://go.dev/play/p/ttBvq1V7qyH
