### ISSUE TITLE
Could you make redirects for the website?

### ISSUE THREAD

**Issue by sixcorners** [triggermesh/triggermesh#949]
Could you make https://triggermesh.io/ and https://www.triggermesh.io/ redirect to https://cloud.triggermesh.io/?

**Comment by tzununbekov** [comment]
@sixcorners thanks for filing the issue
@sameersbn what do you think? I agree that having a root domain that does not resolve to anything is not really useful

**Comment by sebgoa** [comment]
Let's redirect to triggermesh.com
