### ISSUE TITLE
Consider adding dependencies in Function CRDs

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/triggermesh#962]
It was decision on our side to have a simple Function CRD for event manipulation.

However if you want to do more than simple event manipulation you may need to load a dependency for your function code to run.

In the case of a Python function for example it would be nice to be able to provide a set of modules that can be installed via Pip.

in Kubeless we used to do this via an init-container which would load the modules into a specific directory defined in the environment of the runtime.

**Comment by JeffNeff** [comment]
What if we just ask the people that require dependencies to use the kn func project?

It is easy to bootstrap a new cloud event project with `func create -l go -t cloudevents <project-name>`

they support several languages as well :
```
  go
  node
  python
  quarkus
  rust
  springboot
  typescript
  ```

**Comment by sebgoa** [comment]
it is definitely one option. 

However, some folks like to write the function in-line within a CR
