### ISSUE TITLE
set http proxy for connecting to azureservicebustopicsource.sources.triggermesh.io

### ISSUE THREAD

**Issue by davidkarlsen** [triggermesh/triggermesh#963]
How can one instruct the triggermesh container to use a http-proxy in order to connect to a servicebus topic?

**Comment by davidkarlsen** [comment]
@yes, see #964 which is a generic problem-statement with according PR which should fix this.

**Comment by davidkarlsen** [comment]
Closing as #964 is fixed.

**Comment by sebgoa** [comment]
I am still a bit curious to make sure this works. The env var will be set but I don't know if the code will actually honor it.

**Comment by davidkarlsen** [comment]
> I am still a bit curious to make sure this works. The env var will be set but I don't know if the code will actually honor it.

it will work for things that use vanilla http-comms, but probably not when using amqp which is TCP oriented. I guess it would work if using websockets, but I don't think the adapter does that. 

Nevertheless, it is useful to be able to inject various env-vars.
